version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    env_file:
      - .env.development.local
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.development.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fiora
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
